### PR TITLE
Added import for multiple attributes

### PR DESCRIPTION
**Pull request by almssp**
Usage:
resource "sonarcloud_user_group_member" "all" {
  group = "Members"
  login ="user@github"
}
terraform import "sonarcloud_user_group_member.all[\"user@github\"]" "user@github,Members"

### CODE REVIEW

**Review by reinoudk — CHANGES_REQUESTED** [review]
Nice addition! 

I have one remark: could you run `make fmt` to ensure that the code has consistent formatting?

**Comment by almssp** [comment]
Commited.

Thanks a lot.

**Review by reinoudk — APPROVED** [review]
LGTM. I have added the issue to the `v0.3.0` milestone, I hope to build a new release either today or this weekend.

**Comment by almssp** [comment]
Great..
Thank you.

The ideia is in case you want to import your current user settings into terraform and manage from terraform instead of the web ui
You would have to loop the import command and import each user and each group that user belongs too.

In case User 1 is in group Admins and Members(Default)
You would have two imports.

Import user1,Members
Import user1,Admins

From previous providers I used in the past, they follow pretty much the same behaviour
You need a unique ID per user / group.

Thanks again for the quick reply.

I also want to take a look at the permissions at the project level.
Mainly we are integrating our access-control systems and sonar cloud is one of them, but we do have more granular permissions at project level.

Regards
Andre

**Comment by reinoudk** [comment]
@almssp I've created a patch release (v0.2.1) for this. The resource import is now available in the latest version: https://registry.terraform.io/providers/rewe-digital/sonarcloud/latest/docs/resources/user_group_member#import. 

Thanks again for the addition!

**Comment by almssp** [comment]
Brilliant!
I’ve done some investigation regarding permissions, there is no API to read
the permissions, only add.
So this one will have to take a backseat for now until sonarcloud
officially release something.

**Pull request merged**
